#!/usr/bin/env ruby

git_bundles = %Q{
  git://github.com/astashov/vim-ruby-debugger.git
  git://github.com/ervandew/supertab.git
  git://github.com/godlygeek/tabular.git
  git://github.com/depuracao/vim-rdoc.git
  git://github.com/msanders/snipmate.vim.git
  git://github.com/pangloss/vim-javascript.git
  git://github.com/scrooloose/nerdtree.git
  git://github.com/timcharper/textile.vim.git
  git://github.com/tpope/vim-cucumber.git
  git://github.com/tpope/vim-fugitive.git
  git://github.com/tpope/vim-git.git
  git://github.com/tpope/vim-haml.git
  git://github.com/tpope/vim-markdown.git
  git://github.com/tpope/vim-rails.git
  git://github.com/tpope/vim-repeat.git
  git://github.com/tpope/vim-surround.git
  git://github.com/tpope/vim-vividchalk.git
  git://github.com/davidoc/taskpaper.vim.git
  git://github.com/tsaleh/vim-matchit.git
  git://github.com/tsaleh/vim-shoulda.git
  git://github.com/jmartindf/vim-tcomment.git
  git://github.com/tsaleh/vim-tmux.git
  git://github.com/vim-ruby/vim-ruby.git
  git://github.com/vim-scripts/Gist.vim.git
  git://github.com/gmarik/vundle.git
  git://github.com/vadv/rubycomplete.git
  git://github.com/jnwhiteh/vim-golang.git
  git://github.com/Blackrush/vim-gocode.git
  git://github.com/majutsushi/tagbar.git
  git://github.com/vim-scripts/dbext.vim.git
  git://github.com/jlanzarotta/bufexplorer.git
  git://github.com/vim-scripts/winmanager--Fox.git
  git://github.com/Valloric/YouCompleteMe.git
}.split(/\n/).map{|x| x.strip }.delete_if{|x| x.to_s.size == 0}


vim_org_scripts = [
  ["IndexedSearch", "7062",  "plugin"],
  ["jquery",        "12107", "syntax"],
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.cd(bundles_dir)

puts "trashing everything (lookout!)"
Dir["*"].each {|d| FileUtils.rm_rf d }

git_bundles.each_with_index do |url,idx|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "unpacking #{url} into #{dir} (#{idx+1}/#{git_bundles.size})"
  `git clone #{url} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git"))
end

vim_org_scripts.each do |name, script_id, script_type|
  puts "downloading #{name}"
  local_file = File.join(name, script_type, "#{name}.vim")
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
end



